#!/usr/bin/env node
/**
 * Produce store-ready archives from the built platform directories.
 *
 *   dist/FMHY-Similar-chromium-<version>.zip   Chrome Web Store
 *   dist/FMHY-Similar-firefox-<version>.xpi    Firefox Add-ons (a zip, by convention)
 *
 * Usage: node tools/package.mjs
 */

import path from 'node:path';
import { execFile } from 'node:child_process';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { promisify } from 'node:util';
import { exists, PLATFORM, readJSON } from './lib.mjs';

const run = promisify(execFile);

const DIST = path.join(process.cwd(), 'dist');
const pkg = await readJSON(path.join(process.cwd(), 'package.json'));

await mkdir(DIST, { recursive: true });

const targets = [
  { platform: 'chromium', ext: 'zip' },
  { platform: 'firefox', ext: 'xpi' }
];

const built = [];
for (const { platform, ext } of targets) {
  const dir = path.join(PLATFORM, platform);
  const manifestPath = path.join(dir, 'manifest.json');
  if (!exists(manifestPath)) {
    console.error(`\x1b[31m✗\x1b[0m ${dir} is missing — run \`node tools/build.mjs\` first.`);
    process.exit(1);
  }
  const manifest = await readJSON(manifestPath);
  if (manifest.version !== pkg.version) {
    console.error(`\x1b[31m✗\x1b[0m version mismatch: manifest ${manifest.version} vs package.json ${pkg.version}`);
    process.exit(1);
  }

  const out = path.join(DIST, `FMHY-Similar-${platform}-${manifest.version}.${ext}`);
  await rm(out, { force: true });
  // `-x` keeps macOS junk out of store submissions; the zip root must be the
  // manifest itself, so we run zip with the platform directory as cwd.
  await run('zip', ['-r', '-X', '-q', out, '.', '-x', '.DS_Store', '-x', '__MACOSX/*'], { cwd: dir, maxBuffer: 1 << 24 });
  const bytes = (await readFile(out)).length;
  built.push({ platform, out, manifest, mb: (bytes / 1024 / 1024).toFixed(2) });
}

// A signed-source copy is not produced here; AMO/CWS handle signing on upload.
const summary = built.map(({ platform, out, manifest, mb }) =>
  `  ${platform.padEnd(9)} ${path.relative(process.cwd(), out).padEnd(46)} ${mb} MB  v${manifest.version}`
).join('\n');

await writeFile(
  path.join(DIST, 'README.md'),
  `# Build output\n\nGenerated by \`npm run package\` — do not edit or commit.\n\n${summary}\n`
);

console.log(`\x1b[32m✓\x1b[0m packaged ${built.length} archives\n${summary}\n`);
